apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brewer
  template:
    metadata:
      labels:
        app: brewer
    spec:
      containers:
      - image: denisvitez/rso-brewers:latest
        name: brewers
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://18.236.151.24:5432/brewers
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: KUMULUZEE_DATASOURCES0_PASSWORD
        ports:
        - containerPort: 5100
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: brewer
spec:
  type: LoadBalancer
  ports:
  - port: 5100
    protocol: TCP
    targetPort: 5100
  selector:
    app: brewer